### ISSUE TITLE
Readme updates for playgrounds - The active toolchain is not compatible with playgrounds. libswiftCore.dylib could not be loaded

### ISSUE THREAD

**Issue by johndpope** [tensorflow/swift-models#10]
Need to spell out to use macOS playground . - not  iOS playground.

https://github.com/tensorflow/swift/issues/23

**Comment by rxwei** [comment]
Would you like to start a PR?

**Comment by johndpope** [comment]
so used to adding c/c++ flags over course of my career - I see swift flags buried in settings - makes sense.  need to spell this out too. 
<img width="720" alt="screen shot 2018-06-08 at 17 24 55" src="https://user-images.githubusercontent.com/289994/41181783-00c2202c-6b41-11e8-8bc2-62cedbeba99c.png">


then I get these errors. 
<img width="1085" alt="screen shot 2018-06-08 at 17 26 07" src="https://user-images.githubusercontent.com/289994/41181792-0d0c1ac2-6b41-11e8-8cc9-fc10f8968923.png">

definitively have the right toolchain selected.
<img width="1015" alt="screen shot 2018-06-08 at 17 30 04" src="https://user-images.githubusercontent.com/289994/41181932-9cfd5a88-6b41-11e8-9294-10958df167f6.png">

**Comment by johndpope** [comment]
related https://groups.google.com/a/tensorflow.org/forum/#!msg/swift/c2fBWN3stzg/thSQM9DpAgAJ

**Comment by johndpope** [comment]
this is the documentation for xcode project - we should glue this here into readme 

not sure there's an easy way to grab the marvelous formatted response from @frogcjn -  https://github.com/tensorflow/swift/issues/10#issuecomment-385167803

<img width="457" alt="screen shot 2018-06-08 at 17 52 40" src="https://user-images.githubusercontent.com/289994/41182696-c2fb81f8-6b44-11e8-8392-4830db5d4fd1.png">
<img width="459" alt="screen shot 2018-06-08 at 17 52 36" src="https://user-images.githubusercontent.com/289994/41182697-c3067d24-6b44-11e8-9852-960fe63b507e.png">
<img width="456" alt="screen shot 2018-06-08 at 17 52 30" src="https://user-images.githubusercontent.com/289994/41182698-c3108ac6-6b44-11e8-8897-f8c8d4e27900.png">

**Comment by johndpope** [comment]
we might be able to use https://github.com/yonaskolb/XcodeGen to save the day this manual boiler plate stuff.

brew tap yonaskolb/XcodeGen https://github.com/yonaskolb/XcodeGen.git
brew install XcodeGen

https://github.com/num42/RxUserDefaults/blob/master/project.yml

**Comment by rxwei** [comment]
We made clear that playgrounds are macOS-only. This has been documented in usage instructions also.
