### ISSUE TITLE
0.3 models pass

### ISSUE THREAD

**Issue by brettkoonce** [tensorflow/swift-models#101]
@rxwei Did a quick pass:

  - ~~Transformer has a bunch of Int32 calls that will need to be updated~~ v2: #113 thanks @leoxzhao!
  - ~~MiniGo will require some ❤️ -> #114~~
  - ~~Autoencoder: see #93~~

Rest seem to be working!

**Comment by rxwei** [comment]
Thanks a ton, Brett!

**Comment by leoxzhao** [comment]
I updated Transformer model to work with April 16, 2019 Xcode toolchain (swift-tensorflow-DEVELOPMENT-2019-04-16-a-osx.pkg).

**Comment by brettkoonce** [comment]
Transformer will require some tweaks to work with new layers api, very specifically in making AttentionInput play nice with being defined as a differentiable type.

**Comment by brettkoonce** [comment]
@rxwei Transformer will require some tweaks to work with new layers api, very specifically in making AttentionInput play nice with being defined as a differentiable type.

#109, #110, #111 and #112 bring everything else forward (sans above).

**Comment by leoxzhao** [comment]
I just read the callable proposal a few days ago. Now `Layer` is using it in April 18 Development Snapshots. This is fast. I am working on updating Transformer.

**Comment by brettkoonce** [comment]
@leoxzhao cool!

**Comment by leoxzhao** [comment]
Static callable (April 18 Xcode 10 Development Snapshot) has issue to handle `inout` parameter, which blocks Transformer model since it uses `inout` in a few places. I filed a bug at bugs.swift.org (https://bugs.swift.org/browse/TF-443).

**Comment by brettkoonce** [comment]
@leoxzhao good find, nice testcase!

**Comment by leoxzhao** [comment]
I played Go in university, but I was not an enthusiast. I left the MiniGo model for a few days to see if someone who really loved the game would claim it. A few days have passed, and nobody's claimed the model, so I've decided to take it.

**Comment by rxwei** [comment]
The main author of Swift MiniGo (@xiejw) is also working on migrating it AFAIK. @xiejw, what's the current progress and is there anything we can help with? Perhaps someone can start a PR and we can iterate on it together?

**Comment by rxwei** [comment]
Thanks for pushing this forward!

**Comment by rxwei** [comment]
Now that everything's done, I'm going to close this issue now! Huge thanks to @brettkoonce for coordinating this.

We've just released [version 0.3](https://github.com/tensorflow/swift/blob/master/RELEASES.md#version-03). Now it's time to merge `master` back into `stable`! I started #124 to track this task.
