### ISSUE TITLE
Enhancement - MNIST example - showcase protocol Learnable/Optimizer for gradient / loss / learningRate 

### ISSUE THREAD

**Issue by johndpope** [tensorflow/swift-models#11]
https://www.tensorflow.org/api_docs/swift/Protocols/Learnable
![screen shot 2018-06-11 at 10 03 20](https://user-images.githubusercontent.com/289994/41236264-b0938940-6d5e-11e8-85ab-f25dba27757b.png)

People picking up this sample repo will likely sprawl the wrong style of code unless good guidance is provided.

![screen shot 2018-06-11 at 10 06 55](https://user-images.githubusercontent.com/289994/41236454-30744a0a-6d5f-11e8-99be-4a90ae91b84c.png)

was there more sample  code associated with this and other protocols (optimizer) that we can cherry pick?

here there's a bunch of code that seems messy lakes the DifferentiableModule inheritance compared to perceptron sample. 
![screen shot 2018-06-11 at 10 11 05](https://user-images.githubusercontent.com/289994/41236728-cf340342-6d5f-11e8-8cf9-a61a404870e4.png)

**Comment by johndpope** [comment]
maybe the docs are out of date - are these protocols still relevant?

![screen shot 2018-06-11 at 10 19 57](https://user-images.githubusercontent.com/289994/41237236-0af57202-6d61-11e8-88c3-0d952369ca54.png)

**Comment by mhong** [comment]
John, thanks for bringing this to our attention.

@rxwei @dan-zheng Should we remove the doc, now that we removed the experimental high level API?

**Comment by johndpope** [comment]
I think removing docs will need a new ticket - I'll close this enhancement ticket for now. 
The javascript docs look quite good - you guys internally should put heads together.
![screen shot 2018-06-11 at 10 25 59](https://user-images.githubusercontent.com/289994/41237583-e02c3c94-6d61-11e8-9beb-edfd57bd394a.png)

**Comment by dan-zheng** [comment]
The high-level APIs were experimental and have been removed.
Here's the [mailing list announcement](https://groups.google.com/a/tensorflow.org/forum/#!topic/swift/8fuBSJ0Vocs).

I'll update the API docs this week.
