### ISSUE TITLE
Merge 'master' into 'stable' for v0.3.

### ISSUE THREAD

**Issue by rxwei** [tensorflow/swift-models#124]
We've just released [version 0.3](https://github.com/tensorflow/swift/blob/master/RELEASES.md#version-03). Now it's time to merge `master` into `stable`!

**Comment by BradLarson** [comment]
Given that we did merge the 0.5 branch into stable, and are about to do this for 0.6, this issue might be slightly obsolete. Sorry for not cleaning this up when we took care of 0.5.
