### ISSUE TITLE
macOS troubleshooting

### ISSUE THREAD

**Issue by rxwei** [tensorflow/swift-models#126]
## macOS Troubleshooting
If you see `TensorFlow not found` when building samples from command line or 
```shell
<unknown>:0: error: cannot load underlying module for 'Darwin'
<unknown>:0: note: did you forget to set an SDK using -sdk or SDKROOT?
<unknown>:0: note: use "xcrun swiftc" to select the default macOS SDK installed with Xcode
  ```
make sure you've added the correct version of `swift` to your path.
eg. 
```shell
which swift
/usr/bin/swift # This is the wrong path!
```
The swift binary should be referencing the most updated toolchain bin path eg. 
```shell
export PATH="/Library/Developer/Toolchains/swift-latest/usr/bin/:$PATH"
which swift
/Library/Developer/Toolchains/swift-latest/usr/bin/swift
```

**Comment by johndpope** [comment]
Hi Richard,

so above note should read 
export PATH=/Library/Developer/Toolchains/swift-latest/usr/bin:"${PATH}"
NOT
export PATH=/Library/Developer/Toolchains/swift-latest/usr/bin/:"${PATH}"
my bad.


I've configured this - and can successfully build - 
but dropping into the sample for Transformer - ran into problem which references xcrun 
for some reason - even though my xcode is correctly pointing to latest toolchain / command line is off.
But the instructions here don't go far enough (xcode 10.1  / majove). 

**Selecting a Swift toolchain affects the Xcode IDE only. To use the Swift toolchain with command-line tools, add the Swift toolchain to your path as follows:**

I set path  - but still run into 
<unknown>:0: error: cannot load underlying module for 'Darwin'
<unknown>:0: note: did you forget to set an SDK using -sdk or SDKROOT?
<unknown>:0: note: use "xcrun swiftc" to select the default macOS SDK installed with Xcode
(There maybe a better way to do this but I had to dig out the toolchain bundle identifier and pass into xcrun. maybe it's just my setup? )


https://github.com/tensorflow/swift/blob/master/Installation.md

![Screen Shot 2019-04-30 at 11 32 27 pm](https://user-images.githubusercontent.com/289994/56965279-3cc51880-6ba0-11e9-8c8d-2d6fe7ac1e2a.png)

```shell

 swift -O -ltensorflow -o main Operators.swift Model.swift PythonCheckpointReader.swift main.swift
Operators.swift:20:2: error: unknown attribute 'differentiable'
@differentiable
 ^
Operators.swift:28:2: error: unknown attribute 'differentiable'
@differentiable(
 ^
Operators.swift:79:6: error: unknown attribute 'differentiable'
    @differentiable(wrt: self, vjp: _vjpGathering)
     ^
Operators.swift:15:8: error: no such module 'TensorFlow'
import TensorFlow
(base) ➜  Transformer git:(master) ✗ which swiftc
/Library/Developer/Toolchains/swift-latest/usr/bin/swiftc
(base) ➜  Transformer git:(master) ✗ swiftc -O -ltensorflow -o main Operators.swift Model.swift PythonCheckpointReader.swift main.swift
<unknown>:0: error: cannot load underlying module for 'Darwin'
<unknown>:0: note: did you forget to set an SDK using -sdk or SDKROOT?
<unknown>:0: note: use "xcrun swiftc" to select the default macOS SDK installed with Xcode
(base) ➜  Transformer git:(master) ✗ xcrun swiftc
<unknown>:0: error: no input files
(base) ➜  Transformer git:(master) ✗ swiftc -O -ltensorflow -o main Operators.swift Model.swift PythonCheckpointReader.swift main.swift
<unknown>:0: error: cannot load underlying module for 'Darwin'
<unknown>:0: note: did you forget to set an SDK using -sdk or SDKROOT?
<unknown>:0: note: use "xcrun swiftc" to select the default macOS SDK installed with Xcode
(base) ➜  Transformer git:(master) ✗ swiftc  -ltensorflow -o main Operators.swift Model.swift PythonCheckpointReader.swift main.swift
<unknown>:0: error: cannot load underlying module for 'Darwin'
<unknown>:0: note: did you forget to set an SDK using -sdk or SDKROOT?
<unknown>:0: note: use "xcrun swiftc" to select the default macOS SDK installed with Xcode
(base) ➜  Transformer git:(master) ✗ swiftc  -ltensorflow main Operators.swift Model.swift PythonCheckpointReader.swift main.swift
<unknown>:0: error: no such file or directory: 'main'
(base) ➜  Transformer git:(master) ✗ swiftc -O -ltensorflow -o main Operators.swift Model.swift PythonCheckpointReader.swift main.swift
<unknown>:0: error: cannot load underlying module for 'Darwin'
<unknown>:0: note: did you forget to set an SDK using -sdk or SDKROOT?
<unknown>:0: note: use "xcrun swiftc" to select the default macOS SDK installed with Xcode
(base) ➜  Transformer git:(master) ✗ swift --version
Swift version 5.0-dev (LLVM dcb9eb74a7, Clang 95cdf7c9af, Swift 4c94878dd2)
Target: x86_64-apple-darwin18.5.0
(base) ➜  Transformer git:(master) ✗ which swift
/Library/Developer/Toolchains/swift-latest/usr/bin/swift
(base) ➜  Transformer git:(master) ✗ xcrun -f swift
/Applications/Xcode.app/Contents/Developer/Toolchains/**XcodeDefault.xctoolchain**/usr/bin/swift
(base) ➜  Transformer git:(master) ✗ export TOOLCHAINS=swift
(base) ➜  Transformer git:(master) ✗ swiftc  -ltensorflow main Operators.swift Model.swift PythonCheckpointReader.swift main.swiftc
(base) ➜  Transformer git:(master) ✗ xcrun -f swift
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift
(base) ➜  Transformer git:(master) ✗  export PATH=/Library/Developer/Toolchains/swift-latest/usr/bin:"${PATH}"
(base) ➜  Transformer git:(master) ✗ xcrun -f swift
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift
```

I managed to resolve this by digging out the bundle identifier - and appending to xcrun command 
eg. **com.google.swift.20190423**
![Screen Shot 2019-04-30 at 11 29 57 pm](https://user-images.githubusercontent.com/289994/56965130-e8ba3400-6b9f-11e9-9e47-b5ce61aea701.png)

**xcrun --toolchain "com.google.swift.20190423" swiftc -O -ltensorflow -o main Operators.swift Model.swift PythonCheckpointReader.swift main.swift**

**Comment by leoxzhao** [comment]
This is how I use Swift for TensorFlow. It works on Mojave (I worked for High Sierra too before I upgraded).
Open Terminal (You can add it into your .bash_profile if you only use Swift command line for deep learning purpose.

```sh
export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
export SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk
export PATH=/Library/Developer/Toolchains/swift-tensorflow-RELEASE-0.3-a.xctoolchain/usr/bin:$PATH
```

After that, you can run 

```sh
cd Transformer
swiftc -O -ltensorflow -o main Operators.swift Model.swift PythonCheckpointReader.swift main.swift
```

You can use `swift` command in the same way.

**Comment by johndpope** [comment]
The discrepancy I can see is in the transformer repo / it spells out to use 
xcrun swiftc  .....
Not simply swiftc. 
Xcrun seems to default to 10.4 toolchain irrespective of Xcode being configured to use tensorflow toolchain correctly. If you run xcrun swiftc - does it compile or throw error? 
We need to update the transformer readme to drop xcrun or append it with notes on using correct toolchain.

**Comment by johndpope** [comment]
thx @leoxzhao  this resolves SDKROOT problem.

export SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk

do you know of any problems if you don't spell out export  DEVELOPER_DIR? DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer

**Comment by leoxzhao** [comment]
I just tried to set DEVELOPER_DIR to "". `swift` seems working fine. I probably added it with SDKROOT to give Swift for TensorFlow same environment variables as toolchain comes with Xcode. Just SDKROOT seems adequate.

**Comment by 8bitmp3** [comment]
Hey @rxwei 🙌 Do you think it makes sense for you or someone from the team to close this issue since it was opened all the way back in April 2019? A bunch of questions related to macOS have been answered on on `/tensorflow/swift` under Closed Issues and the Swift for TF Google Group under "Error while importing TensorFlow". Plus, with one of the latest nightly builds, macOS toolchains appear to work with Xcode's new build system now (no more selecting the legacy build) (thanks @dan-zheng).

**Comment by saeta** [comment]
+1 this seems stale; closing this out. For folks who have issues, please open new tickets. Thanks all!
