### ISSUE TITLE
Use PascalCase for all file names.

### ISSUE THREAD

**Issue by rxwei** [tensorflow/swift-models#133]

**Comment by johndpope** [comment]
If possible, would be neat to have main.swift in each example. This way - using tool like Xcodegen you can easily spit out a corresponding Xcode project all configured.

**Comment by rxwei** [comment]
Yes, PascalCasing shouldn't apply to main.swift files as they are the entry point for each executable product.

**Comment by kirillbobyrev** [comment]
@rxwei for the reference: does "all file names" include Bash scripts (e.g. `Transformer/download_model.sh`) and Python sources (e.g. `Transformer/encoder.py`) or is my assumption that this only relates to Swift sources correct?

**Comment by rxwei** [comment]
It only applies to Swift file names, yes. Thanks for checking!
