### ISSUE TITLE
Neural style transfer example

### ISSUE THREAD

**Issue by saeta** [tensorflow/swift-models#146]
It'd be great to have an example for how to do neural style transfer incorporated into our example models.

**Comment by brettkoonce** [comment]
ping @regrettable-username

**Comment by regrettable-username** [comment]
Hey, I’d be more than happy to take on this task or lend a hand.

**Comment by rxwei** [comment]
We are super happy for you to drive this!

**Comment by regrettable-username** [comment]
Awesome. I'll start converting my style transfer notebook into something more in line with what's already in this repo. I'd like to see if I can get an L-BFGS optimizer working as well. Adam produces decent results but requires a fair amount of hyper parameter tuning depending on the images used.

**Comment by johndpope** [comment]
Have a look at this video by @Hvass-Labs - he has some critique on code (quite scathing on code) - https://www.youtube.com/watch?v=LoePx3QC5Js 

His repo has over 7000 stars.
https://github.com/Hvass-Labs/TensorFlow-Tutorials/blob/master/15_Style_Transfer.ipynb

**Comment by johndpope** [comment]
ok - found this - https://github.com/regrettable-username/style-transfer - looks great @regrettable-username

**Comment by vvmnnnkv** [comment]
Hi @rxwei,
Are you interested in fast style transfer example? It's when then style is learned and then can be applied in one pass. I have inference part working with pretrained weights here 
https://github.com/vvmnnnkv/s4tf-fast-style-transfer

**Comment by saeta** [comment]
@vvmnnnkv definitely interested! Would you be interested in contributing? CC @BradLarson

**Comment by vvmnnnkv** [comment]
@saeta @BradLarson sure! Is there a list of specific code requirements?
What I have is a separate swiftpm package, no image loading or weights loading code is included there (I'm going to import just the model as a library in a back-end service). In [sample notebook](https://github.com/vvmnnnkv/s4tf-fast-style-transfer/blob/master/Demo/Fast_Style_Transfer_with_S4TF.ipynb), images are loaded via SwiftCV and weights are imported using [this separate package](https://github.com/vvmnnnkv/s4tf-model-import), which is probably different from how you want it, e.g. I saw swift-model examples that pass pre-trained weights into constructor. I was experimenting with passing weights into constructor and then with making model conform to Codable protocol, but it's a lot of verbose code, especially when the model contains nested blocks. Additional problems I bumped in with Codable is that a) it requires you to list params explicitly if you don't want to serialize all properties and b) it does not support extra params in the constructor when decoding. So I went with somewhat more "dynamic" (but hacky) method.
As I understand, these common things like images loading/processing and weights import/export are still in the works? If you have some design already, I could try to align existing code to it!

**Comment by BradLarson** [comment]
@vvmnnnkv - Image loading is something that I'm working on breaking out into a standard helper function that we can use across models here. If you just need to load images, and want to do so without OpenCV (SwiftCV), take a look at the `loadImageUsingTensorFlow` function I have here:

https://github.com/BradLarson/AlexNet-Swift/blob/master/AlexNet/ImageDataset.swift

That uses TensorFlow operators to avoid introducing external dependencies.

Weight import / export is also being worked on, and I have a couple of things that I'm experimenting with there. I'm first working on extracting common code in the current models involving dataset loading, then analysis, and then will move on to helper code for weight loading and other capabilities.

While we eventually would like to have notebook examples in parallel with all the command-line projects, all of our examples so far build and run on the command line. Is there a way for this example to do the same?

**Comment by vvmnnnkv** [comment]
@BradLarson - 
>  If you just need to load images, and want to do so without OpenCV (SwiftCV), take a look at the loadImageUsingTensorFlow function I have

Thanks!

> then will move on to helper code for weight loading and other capabilities

Cool! Meanwhile, is there a preferred way to load weights? Currently, I just rely on KeyPathIterable and set weights via `model[keyPath:]`. But weights are loaded from numpy format, this creates Python/Numpy dependency.

> all of our examples so far build and run on the command line. Is there a way for this example to do the same?

Yes - I've added [example app](https://github.com/vvmnnnkv/s4tf-fast-style-transfer/tree/master/Sources/FastStyleTransferDemo) that applies style to jpeg image and saves output as jpeg.

**Comment by BradLarson** [comment]
@vvmnnnkv - Regarding weight loading, you can use the TensorFlow Raw.restoreV2() function to pull in checkpoint files, as used in MiniGo's [PythonCheckPointReader](https://github.com/tensorflow/swift-models/blob/master/MiniGo/Models/PythonCheckpointReader.swift). That limits you to TensorFlow checkpoint files, but would remove a Python dependency.

I've also used binary weight dumps of my own making in [this code](https://github.com/BradLarson/AlexNet-Swift/blob/master/AlexNet/WeightLoading.swift), if you have the means of simply writing out bytes from your trained source.

Again, I'd like to have something better available in the near term.

**Comment by vvmnnnkv** [comment]
@BradLarson -
I can try to use TF checkpoint or perhaps load numpy file with pure Swift (shouldn't be too hard? :))
At which point do you think this model is viable for PR?

**Comment by vvmnnnkv** [comment]
Hi @BradLarson,
Updated #191 to load from TF checkpoints. Numpy archive requires Zip dependency :)

**Comment by brettkoonce** [comment]
Now that #146 is merged can this be closed?

**Comment by BradLarson** [comment]
@brettkoonce - Good point, closing as completed.
