### ISSUE TITLE
GAN example

### ISSUE THREAD

**Issue by saeta** [tensorflow/swift-models#150]
It'd be great to have a generative model incorporated as part of our models repository.

**Comment by QuantumTCode** [comment]
I'll try implementing a GAN example.

**Comment by rxwei** [comment]
Great, thank you!

**Comment by kamalkraj** [comment]
Hi @rxwei ,
I implemented GAN (https://github.com/kamalkraj/swift-models/blob/gan/GAN/main.swift)
But the loss is not changing . The code is ported from (https://github.com/diegoalejogm/gans/blob/master/1.%20Vanilla%20GAN%20PyTorch.ipynb)

@rxwei Could you please take look into it .

**Comment by 8bitmp3** [comment]
Hey @rxwei I see that @t-ae and @BradLarson authored a first GAN example. Are you guys looking for more by any chance? Thanks

**Comment by 8bitmp3** [comment]
https://forums.fast.ai/t/wasserstein-gan-in-swift-for-tensorflow/47635/7 just noticed this fella is working on Wasserstein GAN https://gist.github.com/rahulbhalley/a493d77dd9abf77a4e082fca801f0014#file-wgan-data-s4tf-swift

**Comment by t-ae** [comment]
My example is non-convolutional one, so convolutional GAN would be good.
I think WGAN-GP will be good example of higher-order differentiation (but it's not available currently).
