### ISSUE TITLE
transformer - opengpt - bump 117M -> 345m model

### ISSUE THREAD

**Issue by johndpope** [tensorflow/swift-models#153]
openai have released 345m parameter model. https://twitter.com/OpenAI/status/1124440412679233536?s=20

https://github.com/openai/gpt-2
looks like a case we can simply pass 345M into 
https://github.com/tensorflow/swift-models/blob/master/Transformer/download_model.sh#L4

Need to test this loads - will try later today.
https://github.com/tensorflow/swift-models/blob/a53966a2352d387ca74434c6a555883570691ba3/Transformer/main.swift#L20

**Comment by johndpope** [comment]
I updated 117M -> 345M

Input to reshape is a tensor with 3072 values, but the requested shape has 3060

```swift
let encoder = Python.import("encoder").get_encoder("345M")
let checkpoint = "models/345M/model.ckpt"
let model = TransformerLM(contentsOfPythonCheckpointFile: checkpoint, scope: "model")
```
it compiles fine - but ....

```shell
➜  Transformer git:(master) ✗ swiftc -O -ltensorflow -o main Operators.swift Model.swift PythonCheckpointReader.swift main.swift

➜  Transformer git:(master) ✗ ./main 0.9 "skynet"
INFO: 🐍 conda environment: gymai
skynetpytok: [8135, 2047, 316]
Fatal error: Input to reshape is a tensor with 3072 values, but the requested shape has 3060: file /usr/local/src/swift-build/swift/stdlib/public/TensorFlow/CompilerRuntime.swift, line 2108
```

Fatal error: Input to reshape is a tensor with 3072 values

**Comment by leoxzhao** [comment]
#154

**Comment by johndpope** [comment]
1.5 billion parameters will drop shortly - https://github.com/ConnorJL/GPT2

https://medium.com/@NPCollapse/replicating-gpt2-1-5b-86454a7f26af

Let's do this - @ConnorJL

**Comment by ConnorJL** [comment]
Hi John, I think there is a bit of confusion here I'm sorry. As explained in my [follow up post](https://medium.com/@NPCollapse/the-hacker-learns-to-trust-62f3c1490f51), I actually don't plan on releasing 1.5B anymore, at least until OpenAI decides to release theirs. Sorry for the confusion.
