### ISSUE TITLE
dyld: Library not loaded: @rpath/libswiftPython.dylib  on MacOS

### ISSUE THREAD

**Issue by tonymaniaci** [tensorflow/swift-models#159]

**Comment by tonymaniaci** [comment]
dyld: Library not loaded: @rpath/libswiftPython.dylib
  Referenced from: /Users/tonymaniaci/Library/Developer/Xcode/DerivedData/moose2-bhlgnwyychpywtcuymrlparbuhng/Build/Products/Debug/moose2
  Reason: image not found
(lldb)

**Comment by jbednarik1** [comment]
Same issue here.
`
Legacy Build System
macOS 10.14.4
Command Line Tools: 10.2.1
Always Embed Swift Stardard Libraries: Yes
`

**Comment by tbass134** [comment]
Same issue as well

**Comment by matheusalano** [comment]
Same here.

**Comment by rxwei** [comment]
How did you open the project?

**Comment by matheusalano** [comment]
@rxwei Sorry, are you asking how I opened a new project? If so, Xcode >> New Project >> macOS >> Command Line Tool.

After that, I followed the instructions from `https://github.com/tensorflow/swift/blob/master/Installation.md`

**Comment by rxwei** [comment]
@matheusalano  Thanks for providing the context. There seem to be two different problems here: one could be running this error when compiling tensorflow/swift-models (since this is in the swift-models repository), and the other is compiling a newly created Xcode project like you described. For the latter, could you please file a separate bug in [tensorflow/swift](https://github.com/tensorflow/swift)?

**Comment by rahulbhalley** [comment]
Anyone still having this problem may look at [this](https://github.com/tensorflow/swift/issues/177#issuecomment-569477582) solution.

**Comment by dan-zheng** [comment]
Closing now. This issue seems relevant (maybe only) for macOS Catalina. [The fix](https://github.com/tensorflow/swift/issues/177#issuecomment-569477582) (from right above):

> In Xcode, checkmark **Signing & Capabilities > Hardened Runtime > Disable Library Validation** under Target setting of your project. It resolved this problem for me & I hope it helps others too! Also I did not have to use run script.
> 
> <img alt="Screen Shot 2019-12-29 at 11 15 55 AM" width="869" src="https://user-images.githubusercontent.com/9640948/71552988-2623d980-2a2d-11ea-8b46-69bf44f6a4f9.png">
> 
> Solution was suggested by Daisuke in S4TF mailing list.
