### ISSUE TITLE
Error compiling MNIST.swift

### ISSUE THREAD

**Issue by valeriyvan** [tensorflow/swift-models#16]
MNIST.swift:35:13: error: value of type 'Tensor<Float>' has no member 'toAccelerator'
    return (imagesTensor.toAccelerator(), labelsTensor.toAccelerator())
            ^~~~~~~~~~~~ ~~~~~~~~~~~~~

swift-tensorflow-DEVELOPMENT-2018-06-01-a.xctoolchain
Swift version 4.2-dev (LLVM 04bdb56f3d, Clang b44dbbdf44, Swift 70260a59ef)
Target: x86_64-apple-darwin17.6.0

**Comment by rxwei** [comment]
This is because the toolchain you are using (06-01) is too old. Our APIs are constantly evolving so there will be breaking changes every so often. Please download the latest toolchain [here](https://github.com/tensorflow/swift/blob/master/Installation.md). Thanks!

**Comment by valeriyvan** [comment]
Thank you for your answer. With swift-tensorflow-DEVELOPMENT-2018-06-29-a.xctoolchain having this errors:
MNIST.swift:78:25: error: use of unresolved operator '⊗'
        let z1 = images ⊗ w1 + b1
MNIST.swift:80:21: error: use of unresolved operator '⊗'
        let z2 = h1 ⊗ w2 + b2
MNIST.swift:85:57: error: use of unresolved operator '⊗'
        let dw2 = h1.transposed(withPermutations: 1, 0) ⊗ dz2
MNIST.swift:88:61: error: use of unresolved operator '⊗'
        let dw1 = images.transposed(withPermutations: 1, 0) ⊗ dz1

**Comment by dan-zheng** [comment]
Thanks for the catch! It's been fixed now.

(For reference, matrix multiplication has been renamed from `Tensor.dot(_:)` and `⊗` to `matmul(_:_:)` and `•(_:_:)`. See [this mailing list thread](https://groups.google.com/a/tensorflow.org/forum/#!topic/swift/8fuBSJ0Vocs) for more information.)

**Comment by valeriyvan** [comment]
You were 9min faster then me for fixing this)
