### ISSUE TITLE
Rename 'call' to 'callAsFunction'.

### ISSUE THREAD

**Issue by rxwei** [tensorflow/swift-models#165]
`Layer.call(_:)` has been renamed to `Layer.callAsFunction(_:)` (https://github.com/tensorflow/swift-apis/pull/172) as the result of [SE-0253](https://github.com/apple/swift-evolution/blob/master/proposals/0253-callable.md) proposal review. A toolchain with the new `Layer` definition is [ready for download](https://github.com/tensorflow/swift/blob/master/Installation.md#development-snapshots).

Task: Update all models and layers in this repo to define `func callAsFunction` instead of `func call`.

**Comment by Shashi456** [comment]
@rxwei I think this should be closed, given #166
