### ISSUE TITLE
ReLU implementation in Swift (for TensorFlow / S4TF)

### ISSUE THREAD

**Issue by 8bitmp3** [tensorflow/swift-models#177]
@rxwei your ReLU implementation in Swift 4 TF from forums.fast.ai is great. Unfortunately, it still returns an error with v0.4 in Colab—could it be the compiler issue? I have run the script to upgrade the Colab to the latest S4TF (it should be as of 07/22/19). If there is a current workaround let me know, maybe I missed something.

The issue was first raised here: https://forums.fast.ai/t/implementing-generalrelu-in-swift/44754/11 and I think @marcrasi has looked into it here https://forums.fast.ai/t/s4tf-in-colab-error/44734/6?u=marcrasi

Thanks in advance and great work @rxwei and team

cc @dynamicwebpaige 

```swift
import TensorFlow

struct GeneralReLU: Layer {
    var leak: Float // The slope for X if it's negative
    var subtract: Float  // Used to substract from the final result
    var maxValue: Float // Maximum value

    init(_ leak:Float = 0.0, _ subtract:Float = 0.0, _ maxValue:Float = Float.greatestFiniteMagnitude) {
        self.leak = leak
        subtract = subtract
        maxValue = maxValue
    }
    @differentiable
    func call(_ input: Tensor<Float>) -> Tensor<Float> {
        let positives = max(input, Tensor(0))
        let leaked = min(input, Tensor(0)) * self.leak
        return min(positives + leaked - subtract, Tensor(maxValue))
    }
}
```

**Comment by rxwei** [comment]
`call` has been renamed to `callAsFunction` in 0.4.

**Comment by rxwei** [comment]
See https://github.com/tensorflow/swift-models/issues/165.

**Comment by 8bitmp3** [comment]
Thanks for a swift reply @rxwei 

In Colab, the session crashes—tested a few times. Will run in Xcode later to see if it works there and will get back to you.

(added back the missing`self`s, replaced `call` with `callAsFunction`)
```swift
import TensorFlow

struct GeneralReLU: Layer {
    var leak: Float // The slope for X if it's negative
    var subtract: Float  // Used to substract from the final result
    var maxValue: Float // Maximum value

    init(_ leak:Float = 0.0, _ subtract:Float = 0.0, _ maxValue:Float = Float.greatestFiniteMagnitude) {
        self.leak = leak
        self.subtract = subtract
        self.maxValue = maxValue
    }
    @differentiable
    func callAsFunction(_ input: Tensor<Float>) -> Tensor<Float> {
        let positives = max(input, Tensor(0))
        let leaked = min(input, Tensor(0)) * self.leak
        return min(positives + leaked - subtract, Tensor(maxValue))
    }
}
```

**Comment by rxwei** [comment]
The code compiles file for me locally, but I've also reproduced the Colab crasher. We'll look into it.

**Comment by 8bitmp3** [comment]
> The code compiles fine for me locally, but I've also reproduced the Colab crasher. We'll look into it.

@rxwei it works, closing the issue :) great work!

![image](https://user-images.githubusercontent.com/19637339/63226122-300c1500-c1cf-11e9-8816-b8741f1bad35.png)
