### ISSUE TITLE
Autoencoder's activation should be sigmoid

### ISSUE THREAD

**Issue by t-ae** [tensorflow/swift-models#179]
It's using `tanh` in output layer.

https://github.com/tensorflow/swift-models/blob/08c80a5d797ed771df899169914f84d8dcaa9eec/Autoencoder/main.swift#L93-L94

But input image is [0, 1] ranged.

https://github.com/tensorflow/swift-models/blob/08c80a5d797ed771df899169914f84d8dcaa9eec/Autoencoder/main.swift#L74

In v0.4.0-rc2, if we use sigmoid, this model doesn't learn maybe because there's a bug I fixed but not included yet.
https://github.com/tensorflow/swift-apis/pull/341

It should be replaced in next release.

**Comment by rxwei** [comment]
Feel free to send a PR.
