### ISSUE TITLE
Attribute 'axis' requires a constant argument

### ISSUE THREAD

**Issue by isaacsultan** [tensorflow/swift-models#2]
https://github.com/tensorflow/swift-models/blob/46c2d6bc47b89b3f0abd20089f77c0dfc25b8ae6/MNIST/MNIST.swift#L53

I am recieving a Swift Compiler Error: 'Attribute 'axis' requires a constant argument', when running MNIST model within XCode Version 9.3 (9E145) (macOs).

However, no trouble running the model with the command line.

**Comment by rxwei** [comment]
Did you pass a `-O` flag to the compiler?
