### ISSUE TITLE
Some known problems of the MNIST implmentation

### ISSUE THREAD

**Issue by huan** [tensorflow/swift-models#206]
https://github.com/tensorflow/swift/issues/260#issuecomment-526353706

An improvement list for the MNIST dataset module, from @BradLarson:

1. [x] One big problem is that the current MNIST implementation in the repository lacks shuffling for the batches. The CIFAR10 dataset example has this, for example. 
1. [x] Another is that it currently relies on hardcoded paths, which will break if you take the dataset outside of that project and try to use it in something like Colab.
    * Update: Fixed in #215.
1. [x] Also, there isn't a consistent API in the image classification datasets we have so far, so it would be nice to align the CIFAR10 and MNIST datasets such that they could be closer in that regard. 
1. [x] I don't know how much we want to develop here (vs. in a framework like SwiftAI), but maybe there could be a protocol that image classification datasets could comply to.

**Comment by BradLarson** [comment]
Thanks for tracking this. PR #224 should have fixed the remaining issues, so I'll close this out now.
