### ISSUE TITLE
How could I load a pre-trained model which is trained by python in swift?

### ISSUE THREAD

**Issue by magneter** [tensorflow/swift-models#207]
Hi,I trained a model with tensorflow in python and I want to load it in swift.
How could I do this job?

**Comment by dan-zheng** [comment]
Unfortunately, we don't have a full story for importing pre-trained models from Python yet.

Related TensorFlow checkpoint reader: https://github.com/tensorflow/swift-apis/pull/529
Related discussions: [[1]](https://groups.google.com/a/tensorflow.org/forum/#!msg/swift/zaxfmhZmX-8/aorgIgrNAgAJ) [[2]](https://github.com/tensorflow/swift-apis/issues/25)
