### ISSUE TITLE
Transformer model: _vjpCausallyMasked does not take the enable flag into account

### ISSUE THREAD

**Issue by koen-dejonghe** [tensorflow/swift-models#217]
The enable flag in function _vjpCausallyMasked is not used when calling causallyMasked.
Since the flag defaults to false on the latter function, masking is never executed.

https://github.com/tensorflow/swift-models/blob/41c4a7a782debc8361d1ba7c2de176c9c028b75e/Transformer/Model.swift#L102-L106

Solution:
```
func _vjpCausallyMasked(_ dotProducts: Tensor<Float>, enable: Bool)
    -> (Tensor<Float>, (Tensor<Float>) -> Tensor<Float>) {
    return (causallyMasked(dotProducts, enable:enable), identity)
}
```

**Comment by rxwei** [comment]
Thanks for the bug report! Feel free to send a quick pull request if you like.
