### ISSUE TITLE
Loading MNIST in Google Colab

### ISSUE THREAD

**Issue by rickwierenga** [tensorflow/swift-models#233]
As Brad mentioned in an earlier thread, the current version of S4TF used in Google Colab notebooks is 0.5, so the `tensorflow-0.5` branch of this project should be used.

When I try to load MNIST using the following code:
```swift
let dataset = MNIST(batchSize: 64, flattening: true, normalizing: true)
```

I get this error:
```
Reading data from files: train-images-idx3-ubyte, train-labels-idx1-ubyte.
File not found: train-images-idx3-ubyte
Process killed
```

Is this the case because Colab is running an old version? Is there any workaround for now, or do we have to wait until Colab is updated?

**Comment by BradLarson** [comment]
This is unfortunately an artifact of the older snapshot of the MNIST dataset, which didn't yet have the ability to download and place the appropriate files in the right location. That came in during the 0.5-0.6 interval, so it's only reflected in head and in the tensorflow-0.6 / stable branches.

The U.S. holiday slowed our progress on getting Colab updated, but I'm working on that right now. Sorry for the delay, I know that things are waiting on this.

**Comment by BradLarson** [comment]
Given that this finally went into production earlier this week, and we can now use the latest version of this dataset, I'll close this out.
