### ISSUE TITLE
Add ImageNette dataset

### ISSUE THREAD

**Issue by texasmichelle** [tensorflow/swift-models#237]
ImageNet would be useful to include in this repo, but is very large and difficult to handle both in terms of downloading and processing. Instead, it would be great to have an adapted version of [ImageNette](https://github.com/fastai/imagenette), a much smaller dataset that roughly mirrors the accuracy of ImageNet.

/cc @BradLarson

**Comment by BradLarson** [comment]
As a public note, before anyone else might start working on this, I should have a pull request in within the next day or so to add this dataset. I've been working with [Ayush Agrawal](https://github.com/Ayush517) to add this to swift-models.

**Comment by BradLarson** [comment]
Completed via PR #241, although some more work is needed to reduce peak memory usage.
