### ISSUE TITLE
CIFAR10 on version 0.6 (Colab)

### ISSUE THREAD

**Issue by rickwierenga** [tensorflow/swift-models#254]
I've loaded CIFAR10:
```swift
import Datasets
let dataset = CIFAR10()
```

* How can I count the number of elements of this dataset?
* How can I access the nth element for visualization? I've tried the following:
```swift
dataset.trainingDataset.makeIterator().next()
```

but get this error:
```
error: <Cell 7>:1:40: error: cannot use mutating member on immutable value: function call returns immutable value
dataset.trainingDataset.makeIterator().next()
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
```

**Comment by rickwierenga** [comment]
Apparently counting objects is possible using the `master` version which is currently supported by Colab. Note that this might chance at any point.

```swift
%install-location $cwd/swift-install
%install '.package(url: "https://github.com/tensorflow/swift-models", .branch("master"))' Datasets
```

```swift
import Datasets
let dataset = CIFAR10()
dataset.trainingExampleCount
```

**Comment by saeta** [comment]
@rickwierenga I think if you assign the iterator object itself to a local variable, it will work. Check out this Colab: https://colab.research.google.com/drive/1UjJ6F6cLo5Sv4SczsiM5MNTMvXLmIOlU

Note: In the notebook I also confirmed that using `.branch("master")` does provide `.trainingExampleCount` (and that `.branch("stable")` does not). This functionality will likely go to `stable` on the next release.

Hope this helps!

**Comment by rickwierenga** [comment]
Thanks!

Just made a very small PR to add the test example count: https://github.com/tensorflow/swift-models/pull/255

**Comment by anigasan** [comment]
I made a colab notebook using CIFAR10 based on these inputs: https://colab.research.google.com/drive/1uL-f9AA_0FiNODcQYAmGmykLzpjSL8Cc.

I am wondering if you are planning to write more functions for easier data processing...

**Comment by saeta** [comment]
@anigasan Could you elaborate a bit further on what you're looking for? Thanks!

**Comment by anigasan** [comment]
@saeta never mind!! I had spoken too early without trying all! I was trying to get a sample img and now I could pull from downloaded dataset using iterator.

**Comment by rakesh4real** [comment]
Hi,

In [swift-jupyter colab](https://colab.research.google.com/github/tensorflow/swift/blob/master/notebooks/blank_swift.ipynb),
```
import Datasets
let dataset = CIFAR10()
```
produced error as `CIFAR10()` could not be found.

Solved the problem using
```
%install-location $cwd/swift-install
%install '.package(url: "https://github.com/tensorflow/swift-models", .branch("master"))' Datasets
```
