### ISSUE TITLE
Add citation requirement to datasets

### ISSUE THREAD

**Issue by rickwierenga** [tensorflow/swift-models#286]
We should consider adding a soft requirement for citations. I would suggest adding an optional value `var citation: String? { get }` to ImageClassificationDataset. This should be optional because not every dataset has a citation available.

I'm willing to create a PR for this if the team agrees.

**Comment by BradLarson** [comment]
To date, our tendency has been to add citations to the header comments of models, datasets, and so on. What would be gained by having this inside the code itself? Where would this be read at runtime?

**Comment by rickwierenga** [comment]
You're right. I noticed it was missing here while TFDS had it so I thought it would be a nice addition. But in fact it's not even needed.

We could add BibTeX citations to the files though?

**Comment by saeta** [comment]
Hi @rickwierenga ! I think for now, we'll default to have citations in the doc comments for the datasets, but to keep things simple for now, we'll not yet add a citation field in the protocol requirements. Thanks @rickwierenga !
