### ISSUE TITLE
Compile issue:  Command failed due to signal: Abort trap: 6

### ISSUE THREAD

**Issue by pnorridge** [tensorflow/swift-models#3]
When I try to compile the MNIST example in Xcode I get the error "Command failed due to signal: Abort trap: 6". 

I've attached the compiler messages in case that help.

Thanks.
[Build target MNISTTest_2018-05-05T12-27-37.txt](https://github.com/tensorflow/swift-models/files/1976597/Build.target.MNISTTest_2018-05-05T12-27-37.txt)

**Comment by pnorridge** [comment]
My mistake -- as I was double checking the settings, I realised I'd forgotten to select the -0 flag. Now I've done that it seems to be OK. 

Sorry to waste your time!

**Comment by dan-zheng** [comment]
No worries, glad you figured it out!
