### ISSUE TITLE
MNIST.swift:113:50: error: value of type 'Tensor<Int32>' has no member 'elementsEqual'

### ISSUE THREAD

**Issue by futurejones** [tensorflow/swift-models#30]
`swift -O MNIST.swift ` is failing on Linux - Ubuntu 16.04 - AArch64.

```
Swift version 5.0-dev (LLVM dcb9eb74a7, Clang 95cdf7c9af, Swift ce00e6b128)
Target: aarch64-unknown-linux-gnu
```
```
MNIST.swift:113:50: error: value of type 'Tensor<Int32>' has no member 'elementsEqual'
            let correctPredictions = predictions.argmax(squeezingAxis: 1).elementsEqual(numericLabels)
                                     ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~
```
The same problem also occurs in  `Swift version 4.2-dev` built for AArch64

**Comment by rxwei** [comment]
Hi, we are currently refreshing models and APIs. Expect a brand new set of models soon!

**Comment by wangkuiyi** [comment]
HI @rxwei , Thanks for the prompt reply. Could we run the MNIST.swift example with an earlier version of S4TF? (I suppose that the reported problem is because that @futurejones was using a too recent version, 5.0-dev?)

**Comment by rxwei** [comment]
I believe the latest toolchain works for the MNIST example. We'll update everything in a week or two.

**Comment by skydoorkai** [comment]
> I believe the latest toolchain (01-04) works for the MNIST example. We'll update everything in a week or two.

@rxwei , are you going to update MNIST.swift, or to add elementsEqual support for Tensor?

**Comment by rxwei** [comment]
There's no `elementsEqual` anymore. The operator is now `.==`. Yes, I'm going to update MNIST.

**Comment by rxwei** [comment]
Fixed with the new MNIST: https://github.com/tensorflow/swift-models/blob/stable/MNIST/MNIST.swift.
