### ISSUE TITLE
differentiation of coroutine calls is not yet supported

### ISSUE THREAD

**Issue by pedronahum** [tensorflow/swift-models#326]
Hi,

I am testing S4TF for financial applications given the AD capabilities. And I am facing an issue that i have not seen documented or raised. Your guidance is greatly appreciated.

In particular, when an array is updated in a loop, the code below will fail to compile (S4TF v0.7-rc2 Ubuntu CPU Only). The same code will crash Google Colab. 

```swift
struct PathCalc : Differentiable  {
  @noDerivative let N: Int
  @noDerivative let Nmat: Int
  @noDerivative let Delta: Float
  @noDerivative let Z: Float

  @differentiable(wrt: (Rates, Lambda))
  func applied(Rates:Array<Float>,Lambda:Array<Float> ) -> Array<Float> {

    var L  = Array<Float>(repeating: 0.0,count: N)
    let sq = Delta.squareRoot()

    for n in 0...Nmat-1{
      let sqez = sq*Z
      var v = Float(0)
      
      for i in n+1...N-1{
        let lam = Lambda[i - n - 1 ]
        let con1 = Delta*lam
        v = v + (con1*Rates[i])/(1.0 + Delta*L[i])
        let first = con1*v
        let second = lam*(sqez - 0.5*con1)
        let vrat = exp(first + second)    
	L[i] = Rates[i]*vrat
      }
    }
    return L
  }
 
}

```

If I attempt to get the gradient of the code above, I will get an error
```bash
test.swift:10:4: error: function is not differentiable
  @differentiable(wrt: (Rates, Lambda))
  ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
test.swift:11:8: note: when differentiating this function definition
  func applied(Rates:Array<Float>,Lambda:Array<Float> ) -> Array<Float> {
       ^
test.swift:27:7: note: differentiation of coroutine calls is not yet supported
        L[i] = Rates[i]*vrat
```

Clearly the code above is finance-specific, and it relates to adjoint calculations of financial derivatives (see, for example, http://people.maths.ox.ac.uk/~gilesm/codes/libor_AD/). I just felt that it could be a very good way to raise awareness in the finance industry of the great work you guys are doing here. 

Best,

Pedro N.

**Comment by pedronahum** [comment]
Closing in swift-models, but opening in tensorflow/swift

**Comment by dan-zheng** [comment]
Thanks for sharing your financial application use case! That's quite interesting.

Automatic differentiation is implemented in the Swift compiler, so Issues related to automatic differentiation are actually tracked at https://bugs.swift.org, not at https://github.com/tensorflow/swift. Please file issues there!

Coroutine differentiation support is tracked at TF-1080. [This comment thread from TF-1078](https://bugs.swift.org/browse/TF-1078?focusedCommentId=52682&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-52682) explains your issue and provides a temporary workaround:

> Assignments to `Array` subscripts become calls to the `Array.subscript.modify` accessor. `modify` accessors are coroutines, which require special differentiation support at the Swift Intermediate Language (SIL) level.
> ...
> Before support is added, active applications of coroutines are diagnosed as non-differentiable. In the meantime, you can manually define an inefficient derivative as a workaround:
> ```swift
> extension Array {
>   /// A functional version of `Array.subscript.modify`.
>   /// Differentiation does yet not support `Array.subscript.modify` because
>   /// it is a coroutine.
>   @differentiable(where Element: Differentiable)
>   func updated(at index: Int, with newValue: Element) -> [Element] {
>     var result = self
>     result[index] = newValue
>     return result
>   }
> }
> 
> extension Array where Element: Differentiable {
>   /// An inefficient derivative for a functional version of `Array.subscript.modify`.
>   @derivative(of: updated)
>   func vjpUpdated(at index: Int, with newValue: Element) -> (
>     value: [Element], pullback: (TangentVector) -> (TangentVector, Element.TangentVector)
>   ) {
>     let value = updated(at: index, with: newValue)
>     return (value, { [count = count] v in
>       // `dself`: `v` but with `v[index] = 0`.
>       // `dnewValue`: `v[index]`.
>       var dself = v
>       dself.base[index] = .zero
>       return (dself, v[index])
>     })
>   }
> }
> ```
> Tests:
> ```swift
> @differentiable
> func blahify1(blah: [Float], x: Float) -> Float {
>     var blah = blah
>     // Line below replaces `blah[0] = x * x`.
>     blah = blah.updated(at: 0, with: x * x)
>     return blah[0]
> }
> 
> @differentiable
> func blahify2(blah: [Float], x: Float) -> Float {
>     var blah = blah
>     blah = blah.updated(at: 0, with: blah[0] * x)
>     return blah[0]
> }
> 
> @differentiable
> func blahify3(blah: [Float], x: Float) -> Float {
>     let blah2 = blah.updated(at: 0, with: x)
>     return blah2[0]
> }
> 
> print(valueWithGradient(at: [3], 4, in: blahify1))
> // (value: 16.0, gradient: ([0.0], 8.0))
> print(valueWithGradient(at: [3], 4, in: blahify2))
> // (value: 12.0, gradient: ([4.0], 3.0))
> print(valueWithGradient(at: [3], 4, in: blahify3))
> // (value: 4.0, gradient: ([0.0], 1.0))

> ```

**Comment by pedronahum** [comment]
Hi @dan-zheng 

Many thanks for getting back to me! Greatly appreciated!

Unfortunately, the workaround is not addressing my issue (v0.7-rc2 Ubuntu CPU Only). I get the same compile error, plus an additional warning that "count" was never used in the Array extension. 

Will use JIRA to illustrate the example. 

Thanks,

Pedro N.
