### ISSUE TITLE
New v0.7 toolchain works; `Datasets` compiled with Swift 5.2 "cannot be imported by the Swift 5.1 compiler"

### ISSUE THREAD

**Issue by 8bitmp3** [tensorflow/swift-models#332]
Toolchain: s4tf v0.7 (new).
Xcode: 11.0 (shall I try 11.4?).
Swift: 5.1
Example: VGG16 on Image🐶woof

Error:
`Datasets` module "compiled with Swift 5.2 cannot be imported by the Swift 5.1 compiler..."
<img width="645" alt="image" src="https://user-images.githubusercontent.com/19637339/74895864-b413a500-538a-11ea-9622-23443cf5dd61.png">

Overall, awesome job on v0.7, worked well on another example, the machine got hot during training as expected.

**Comment by BradLarson** [comment]
I don't see this under Xcode 11.0 myself. In cases where I've encountered this error, it was usually due to some weird caching in temporary build directories. Try clearing out .build and / or the DerivedData location for this project and building cleanly just using the 0.7 toolchain.

**Comment by dan-zheng** [comment]
Have you tried a clean Xcode build? (`cmd+shift+k`)
If that doesn't work, could you try deleting `~/Library/Developer/Xcode/DerivedData`?

**Comment by 8bitmp3** [comment]
Aye @BradLarson and @dan-zheng. Cleaning sorted (`cmd+shift+k`) sorted it out. Cheers, wizards you are.

![image](https://user-images.githubusercontent.com/19637339/74963588-e3b5c200-5409-11ea-8236-d75db83c2bef.png)
