### ISSUE TITLE
Evaluate replacing Commander with ArgumentParser in Benchmarks

### ISSUE THREAD

**Issue by BradLarson** [tensorflow/swift-models#354]
Apple recently unveiled the [ArgumentParser](https://swift.org/blog/argument-parser) library for easing the parsing of command-line options. The [Benchmarks](https://github.com/tensorflow/swift-models/tree/master/Benchmarks) target currently uses Kyle Fuller's [Commander](https://github.com/kylef/Commander) to provide a clean interface for command-line options.

[ArgumentParser](https://github.com/apple/swift-argument-parser) provides an intriguing alternative, and seems to have growing support behind it, so we would like to examine if it is practical and desirable to switch from Commander to ArgumentParser within the Benchmarks target. Ideally, we would like to maintain the same command-line options and interface as exists now, so that Benchmarks won't change its interaction with internal test runners.

If Benchmarks could be converted to use ArgumentParser instead, while maintaining the same interface, and the code for doing so looked reasonable, I think we'd welcome a PR that made this change.

**Comment by vguerra** [comment]
I started to play with ArgumentParser when it was announced and tried to use it in this repo .. I was not aware that @BradLarson had created this Issue here ..  but if it is of any help for you @shabalind .. I published what I ended up with here: https://github.com/vguerra/swift-models/commit/3c4e2cc68311c1b7ef9bcdb723d2ea748e30a160

**Comment by shabalind** [comment]
@vguerra Do you mind opening a PR, the changes look like a fix for this issue! 👍

**Comment by vguerra** [comment]
sure @shabalind .. I pushed https://github.com/tensorflow/swift-models/pull/357
