### ISSUE TITLE
GPU perf is much worse than CPU for MNIST

### ISSUE THREAD

**Issue by skydoorkai** [tensorflow/swift-models#36]
With s4tf version 5.0-dev (built from utils/build-toolchain-tensorflow -g), MNIST sample is running much slower with GPU than with CPU. For each epoch, CPU training takes 16 seconds, but GPU training takes 31 seconds.

From nvprof, we can see that the GPU utilization is very low, and there are many GPU/CPU data copies.

![s4tfperf](https://user-images.githubusercontent.com/16055370/52613778-4ce72900-2eca-11e9-958f-f6f06587e2fc.jpg)

Note that MNIST sample is modified as below to make it runnable.
```
            // Update number of correct/total guesses.
            let correctPredictions = predictions.argmax(squeezingAxis: 1) .== numericLabels
            for i in 0...correctPredictions.scalarCount - 1 {
                if correctPredictions.scalars[Int(i)] {
                    correctGuesses += 1
                }
            }
```

Another issue is that the launching time for the first run of GPU code is very slow, takes about 5 minutes. After the first run, there will be no such problems.  We are running in ubuntu docker container.

**Comment by rxwei** [comment]
Will debug soon. The MNIST example is really outdated. I plan to switch this to use the [deep learning library](https://github.com/tensorflow/swift-apis) later this week.

**Comment by jekbradbury** [comment]
There’s a more up-to-date version in the tests for the library Richard linked, but the performance isn’t necessarily a whole lot better.

**Comment by rxwei** [comment]
> There’s a more up-to-date version in the tests for the library Richard linked, but the performance isn’t necessarily a whole lot better.

Oops, I just deleted that test :) I'm about to move it to this repo.

**Comment by rxwei** [comment]
MNIST is updated: Fixed with the new MNIST: https://github.com/tensorflow/swift-models/blob/stable/MNIST/MNIST.swift.

**Comment by Oktai15** [comment]
@rxwei can we close it?
