### ISSUE TITLE
MNIST.swift:41:26: MNist.swift:23:17: MNist.swift:98:13: MNist.swift:114:50:

### ISSUE THREAD

**Issue by zhao15** [tensorflow/swift-models#37]
MNIST.swift is failing on macOS:

$ swift
Welcome to Swift version 5.0-dev (LLVM dcb9eb74a7, Clang 95cdf7c9af, Swift 3fd7afd627).

$ swift -O MNIST.swift
MNIST.swift:41:26: error: use of undeclared type 'ParameterGroup'
struct MNISTParameters : ParameterGroup {
                         ^~~~~~~~~~~~~~
MNist.swift:23:17: error: incorrect argument label in call (have 'numpyArray:', expected 'arrayLiteral:')
    return Array(numpyArray: np.frombuffer(d, dtype: np.uint8))!
                ^~~~~~~~~~~
                 arrayLiteral
MNist.swift:98:13: error: value of type 'MNISTParameters' has no member 'update'
            parameters.update(withGradients: gradients) { param, grad in
            ^~~~~~~~~~ ~~~~~~
MNist.swift:114:50: error: value of type 'Tensor<Int32>' has no member 'elementsEqual'
            let correctPredictions = predictions.argmax(squeezingAxis: 1).elementsEqual(numericLabels)
                                     ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~

**Comment by rxwei** [comment]
Fixed with the new MNIST: https://github.com/tensorflow/swift-models/blob/stable/MNIST/MNIST.swift.
