### ISSUE TITLE
Datasets should not be re-downloaded on each run of a test

### ISSUE THREAD

**Issue by BradLarson** [tensorflow/swift-models#381]
Originally, our intent with the dataset unit tests was to test them from a common starting point each run. That meant manually deleting any locally cached versions of the dataset and forcing a re-download. While that is a noble goal, in practice this is slowing down model tests and using a lot of unnecessary bandwidth.

Therefore, we've decided that it's fine to re-use cached local data for these tests and the code that deletes the locally cached copies of the datasets should be removed from our dataset unit tests.

**Comment by vballoli** [comment]
Shouldn't this line in here: [DatasetUtilities.swift](https://github.com/tensorflow/swift-models/blob/master/Datasets/DatasetUtilities.swift#L42) be changed to `resource.remoteURL` to fix this issue? I noticed that `fetchResource` checks for the file without the `Resource`'s extension ending up with showing that the file always never exists.

**Comment by BradLarson** [comment]
I'm largely referring to cases like the CIFAR10 dataset, which [explicitly is deleted before a test is performed](https://github.com/tensorflow/swift-models/blob/master/Tests/DatasetsTests/CIFAR10/CIFAR10Tests.swift#L9). I believe the BostonHousing dataset also downloads itself each time it is used, because it [does not check if the dataset is present locally](https://github.com/tensorflow/swift-models/blob/master/Datasets/BostonHousing/BostonHousing.swift#L35). Compare with the CIFAR-10 dataset, which normally [does check for this before downloading again](https://github.com/tensorflow/swift-models/blob/master/Datasets/CIFAR10/CIFAR10.swift#L50).

I believe `downloadResource()` itself is performing as intended, because the caching works if set up correctly. Some of the dataset downloading code could be cleaned up, however (and one of my pending pull requests works on part of that).

**Comment by SaiHemanthBR** [comment]
I'm happy to work on this issue.
