### ISSUE TITLE
Move TransformerDemo into Examples

### ISSUE THREAD

**Issue by texasmichelle** [tensorflow/swift-models#387]
Move the remaining code in the Transformer folder into Examples. This could go either in Examples/GPT2-WikiText2 or a new folder along the lines of Examples/GPT2-Generation.

**Comment by BradLarson** [comment]
I started speculating on some renaming in the Readme within PR #377, to bring it closer in line with the GPT2 training model. Agreed that "Transformer" sounds a little too generic now and that it would be nice to continue consolidating examples.
