### ISSUE TITLE
How to export to model?

### ISSUE THREAD

**Issue by starptit** [tensorflow/swift-models#4]
Hi, i've checked out the repository and tried to run command follow to README.md guide in MNIST example. It worked perfectly, but i could not find any exported model. When i looked into source code, seem that there is no exporting function. 
My question is, how to export the result as a model ? I cannot find any documents for this feature (I want something similar to tf.saved_model in Python)

**Comment by VolodymyrPavliukevych** [comment]
Dear @starptit, there is no easy way right now to extract model or raw graph.

> Once the tensor operations are desugared, a transformation we call "partitioning" extracts the graph operations from the program and builds a new SIL function to represent the tensor code. In addition to removing the tensor operations from the host code, new calls are injected that call into our new runtime library to start up TensorFlow, rendezvous to collect any results, and send/receive values between the host and the tensor program as it runs. The bulk of the Graph Program Extraction transformation itself lives in TFPartition.cpp.

> Once the tensor function is formed, it has some transformations applied to it, and is eventually emitted to a TensorFlow graph using the code in TFLowerGraph.cpp. After the TensorFlow graph is formed, we serialize it to a protobuf and encode the bits directly into the executable, making it easy to load at program runtime.

So, actually final graph is serialized in to a protobuf bytes and copied directly into the executable file.
