### ISSUE TITLE
Corrupt zip files 

### ISSUE THREAD

**Issue by vballoli** [tensorflow/swift-models#402]
Hi, I'm trying to download a zip file hosted on a GitHub repository(a dataset), but it's always getting corrupted when I use `downloadResource() ` or use `FoundationNetworking`'s URLSession and download. Any idea how I can fix this ?

P.S. `wget {fileURL}` works fine, so it's not a file problem.

**Comment by brettkoonce** [comment]
can you post code?  have you tried repurposing DatasetUtilities.fetchResource?

**Comment by vballoli** [comment]
I've tried using `download()` directly from `ModelSupport`'s `FileManagement`, but it's the same error, so I'm assuming it's something to do with Swift's `Data` implementation. Here's the code I'm using:

```
import ModelSupport

let url = URL(string: "https://github.com/brendenlake/omniglot/raw/master/python/images_background.zip")!
let localUrl = FileManager.default.temporaryDirectory.appendingPathComponent("Omniglot", isDirectory: true)

do {try download(from: url, to: localUrl)}
catch {print("Error \(error)")}
```

**Comment by SaiHemanthBR** [comment]
This looks like an Ubuntu-specific issue with how Swift handled Data Implementation.
Working fine on macOS.

**Comment by saeta** [comment]
We are also unable to reproduce this issue. If you are able to, please do re-open this ticket.

**Comment by shabalind** [comment]
You need to make sure you have `unzip` installed in your environment. I experienced similar issue in #446.
