### ISSUE TITLE
Adding shufflenetv2

### ISSUE THREAD

**Issue by vballoli** [tensorflow/swift-models#426]
I've worked on ShuffleNetv2's implementation for the swift-models addition. I'm referencing my commit here: 
[https://github.com/vballoli/swift-models/commit/013b8c8139c2b9fffb2b1b14d5c78390d36af99e](https://github.com/vballoli/swift-models/commit/013b8c8139c2b9fffb2b1b14d5c78390d36af99e)

I'd like comments on this before I send a pull request since I'm not sure what's the best way to elegantly handle (apart from directly parameterizing the blocks)[branch implementation](https://github.com/vballoli/swift-models/blob/shufflenet/Models/ImageClassification/ShuffleNetV2.swift#L45) in the InvertedResidual layer.

**Comment by BradLarson** [comment]
Looks like this was resolved by PR #427.
