### ISSUE TITLE
[WordSeg] Fix dropout issues

### ISSUE THREAD

**Issue by sgugger** [tensorflow/swift-models#506]
Currently dropout is not used on the embeddings in the encoder and the decoder because it breaks AD (at least that's what the comment say). See [here](https://github.com/tensorflow/swift-models/blob/a5e1b1d558b174a9590a66b2ffe6978faefff8df/Models/Text/WordSeg/Model.swift#L129) and [there](https://github.com/tensorflow/swift-models/blob/a5e1b1d558b174a9590a66b2ffe6978faefff8df/Models/Text/WordSeg/Model.swift#L175).

**Comment by sgugger** [comment]
So in both case, the dropout should be applied on the matrix of hidden states (I think S4TF returns a list of hidden states and not a matrix batchSize x SequenceLength x hiddenDimension).

**Comment by dan-zheng** [comment]
Dropout added in https://github.com/tensorflow/swift-models/pull/550.
