### ISSUE TITLE
Replace usage of Batcher-based OldMNIST dataset variants

### ISSUE THREAD

**Issue by BradLarson** [tensorflow/swift-models#511]
As an intermediate stage in moving from Batcher to Epochs, @sgugger created new versions of the CIFAR-10 and MNIST datasets (and variants) and retained the existing Batcher-based datasets as OldCIFAR10 and OldMNIST (and variants) until we can move all examples off those old datasets. PR #507 removes the last references to the OldCIFAR10 dataset and that dataset. It will also remove the need for OldMNIST in Benchmarks.

In order to remove the various old MNIST datasets, the following examples also need to be updated:

- [x] **Autoencoder1D**: Autoencoder/Autoencoder1D/main.swift
- [x] **Autoencoder2D**: Autoencoder/Autoencoder2D/main.swift
- [x] **VariationalAutoencoder1D**: Autoencoder/VAE1D/main.swift
- [x] **DCGAN**: DCGAN/main.swift
- [x] **GAN**: GAN/main.swift

 @xihui-wu will take on the conversion of the above.

**Comment by xihui-wu** [comment]
Done. Closing
