### ISSUE TITLE
[WordSeg] One LogSumExp to rule them all

### ISSUE THREAD

**Issue by sgugger** [tensorflow/swift-models#516]
The current implementation of [`computeSemiringScore`](https://github.com/tensorflow/swift-models/blob/a5e1b1d558b174a9590a66b2ffe6978faefff8df/Models/Text/WordSeg/Lattice.swift#L97) computes the LogSumExp of a list of n floats by using n-1 LogSumExp on individual sums which is inefficient (and probably not as numerically stable, at first glance).

`Semiring.swift` should implement a `LogSumExp` on a list of floats and `computeSemiringScore` should use that implementation.

**Comment by Shashi456** [comment]
Love the LOTR reference :P
