### ISSUE TITLE
[BERT] Remove WeightDecayedAdam

### ISSUE THREAD

**Issue by texasmichelle** [tensorflow/swift-models#555]
BERT uses a custom optimizer `WeightDecayedAdam`. All the functionality is covered by the [standard optimizer](https://github.com/tensorflow/swift-apis/blob/master/Sources/x10/swift_bindings/optimizers/Optimizer.swift) from swift-apis, so replace this usage and remove `WeightDecayedAdam`.

**Comment by compnerd** [comment]
@shadaj is looking into this
