### ISSUE TITLE
Minigo: Komi should be 7.5

### ISSUE THREAD

**Issue by amj** [tensorflow/swift-models#56]
Minigo's pre-trained models all assume a komi value of 7.5  Using 6.5 will have surprising results :)

**Comment by xiejw** [comment]
Agreed. We should change that. I will test it and send a PR. 

Thanks for pointing this out!

**Comment by xiejw** [comment]
https://github.com/tensorflow/swift-models/commit/da9ee75fa644baaed06dfeccedab1a9781916458

Fixed. Thanks again.
